// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: translator.proto

package custom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Omitted modes remain unknown; services should explicitly report unsupported modes.
type Support int32

const (
	Support_SUPPORT_UNKNOWN     Support = 0
	Support_SUPPORT_SUPPORTED   Support = 1
	Support_SUPPORT_UNSUPPORTED Support = 2
)

// Enum value maps for Support.
var (
	Support_name = map[int32]string{
		0: "SUPPORT_UNKNOWN",
		1: "SUPPORT_SUPPORTED",
		2: "SUPPORT_UNSUPPORTED",
	}
	Support_value = map[string]int32{
		"SUPPORT_UNKNOWN":     0,
		"SUPPORT_SUPPORTED":   1,
		"SUPPORT_UNSUPPORTED": 2,
	}
)

func (x Support) Enum() *Support {
	p := new(Support)
	*p = x
	return p
}

func (x Support) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Support) Descriptor() protoreflect.EnumDescriptor {
	return file_translator_proto_enumTypes[0].Descriptor()
}

func (Support) Type() protoreflect.EnumType {
	return &file_translator_proto_enumTypes[0]
}

func (x Support) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Support.Descriptor instead.
func (Support) EnumDescriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{0}
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_translator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{0}
}

type CapabilitiesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TextToText     Support                `protobuf:"varint,1,opt,name=text_to_text,json=textToText,proto3,enum=translator.Support" json:"text_to_text,omitempty"`
	FileToText     Support                `protobuf:"varint,2,opt,name=file_to_text,json=fileToText,proto3,enum=translator.Support" json:"file_to_text,omitempty"`
	FileToDocument Support                `protobuf:"varint,3,opt,name=file_to_document,json=fileToDocument,proto3,enum=translator.Support" json:"file_to_document,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_translator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilitiesResponse) GetTextToText() Support {
	if x != nil {
		return x.TextToText
	}
	return Support_SUPPORT_UNKNOWN
}

func (x *CapabilitiesResponse) GetFileToText() Support {
	if x != nil {
		return x.FileToText
	}
	return Support_SUPPORT_UNKNOWN
}

func (x *CapabilitiesResponse) GetFileToDocument() Support {
	if x != nil {
		return x.FileToDocument
	}
	return Support_SUPPORT_UNKNOWN
}

type TranslateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	File          *File                  `protobuf:"bytes,3,opt,name=file,proto3,oneof" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateRequest) Reset() {
	*x = TranslateRequest{}
	mi := &file_translator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateRequest) ProtoMessage() {}

func (x *TranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateRequest.ProtoReflect.Descriptor instead.
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{2}
}

func (x *TranslateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslateRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TranslateRequest) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_translator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{3}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *File) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_translator_proto protoreflect.FileDescriptor

const file_translator_proto_rawDesc = "" +
	"\n" +
	"\x10translator.proto\x12\n" +
	"translator\"\x15\n" +
	"\x13CapabilitiesRequest\"\xc3\x01\n" +
	"\x14CapabilitiesResponse\x125\n" +
	"\ftext_to_text\x18\x01 \x01(\x0e2\x13.translator.SupportR\n" +
	"textToText\x125\n" +
	"\ffile_to_text\x18\x02 \x01(\x0e2\x13.translator.SupportR\n" +
	"fileToText\x12=\n" +
	"\x10file_to_document\x18\x03 \x01(\x0e2\x13.translator.SupportR\x0efileToDocument\"v\n" +
	"\x10TranslateRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12)\n" +
	"\x04file\x18\x03 \x01(\v2\x10.translator.FileH\x00R\x04file\x88\x01\x01B\a\n" +
	"\x05_file\"W\n" +
	"\x04File\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType*N\n" +
	"\aSupport\x12\x13\n" +
	"\x0fSUPPORT_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11SUPPORT_SUPPORTED\x10\x01\x12\x17\n" +
	"\x13SUPPORT_UNSUPPORTED\x10\x022\xa0\x01\n" +
	"\n" +
	"Translator\x12S\n" +
	"\fCapabilities\x12\x1f.translator.CapabilitiesRequest\x1a .translator.CapabilitiesResponse\"\x00\x12=\n" +
	"\tTranslate\x12\x1c.translator.TranslateRequest\x1a\x10.translator.File\"\x00B?Z=github.com/adrianliechti/wingman/pkg/translator/custom;customb\x06proto3"

var (
	file_translator_proto_rawDescOnce sync.Once
	file_translator_proto_rawDescData []byte
)

func file_translator_proto_rawDescGZIP() []byte {
	file_translator_proto_rawDescOnce.Do(func() {
		file_translator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_translator_proto_rawDesc), len(file_translator_proto_rawDesc)))
	})
	return file_translator_proto_rawDescData
}

var file_translator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_translator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_translator_proto_goTypes = []any{
	(Support)(0),                 // 0: translator.Support
	(*CapabilitiesRequest)(nil),  // 1: translator.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 2: translator.CapabilitiesResponse
	(*TranslateRequest)(nil),     // 3: translator.TranslateRequest
	(*File)(nil),                 // 4: translator.File
}
var file_translator_proto_depIdxs = []int32{
	0, // 0: translator.CapabilitiesResponse.text_to_text:type_name -> translator.Support
	0, // 1: translator.CapabilitiesResponse.file_to_text:type_name -> translator.Support
	0, // 2: translator.CapabilitiesResponse.file_to_document:type_name -> translator.Support
	4, // 3: translator.TranslateRequest.file:type_name -> translator.File
	1, // 4: translator.Translator.Capabilities:input_type -> translator.CapabilitiesRequest
	3, // 5: translator.Translator.Translate:input_type -> translator.TranslateRequest
	2, // 6: translator.Translator.Capabilities:output_type -> translator.CapabilitiesResponse
	4, // 7: translator.Translator.Translate:output_type -> translator.File
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_translator_proto_init() }
func file_translator_proto_init() {
	if File_translator_proto != nil {
		return
	}
	file_translator_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_translator_proto_rawDesc), len(file_translator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translator_proto_goTypes,
		DependencyIndexes: file_translator_proto_depIdxs,
		EnumInfos:         file_translator_proto_enumTypes,
		MessageInfos:      file_translator_proto_msgTypes,
	}.Build()
	File_translator_proto = out.File
	file_translator_proto_goTypes = nil
	file_translator_proto_depIdxs = nil
}
