package models

import (
	"encoding/json"
	"net/http"
)

func (h *Handler) handleShow(w http.ResponseWriter, r *http.Request) {
	var req ShowRequest

	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	model, err := h.Model(req.Model)

	if err != nil {
		http.Error(w, err.Error(), http.StatusNotFound)
		return
	}

	result := &ShowResponse{
		ModelInfo: map[string]any{
			"general.basename":     model.ID,
			"general.architecture": "llama",
			"llama.context_length": 262144,
		},

		Capabilities: []string{
			"completion",
			//"vision",
			"tools",
		},

		// Modelfile:  "# Modelfile generated by Ollama",
		// Parameters: "stop \"[INST]\"\nstop \"[/INST]\"\nstop \"<<SYS>>\"\nstop \"<</SYS>>\"",
		// Template:   "{{ if .System }}{{ .System }}{{ end }}{{ if .Prompt }}{{ .Prompt }}{{ end }}{{ .Response }}",
		// Details: ModelDetails{
		// 	Format:            "gguf",
		// 	Family:            "llama",
		// 	Families:          []string{"llama"},
		// 	ParameterSize:     "7B",
		// 	QuantizationLevel: "Q4_0",
		// },
		// ModelInfo: map[string]any{
		// 	"general.architecture": "llama",
		// },
		// ModifiedAt: time.Now(),
	}

	writeJson(w, result)
}
